<?php $title='Beranda';include 'includes/header.php';
$st=['stat_penduduk'=>['Penduduk','users'],'stat_kk'=>['Kepala Keluarga','house-user'],'stat_lk'=>['Laki-laki','person'],'stat_pr'=>['Perempuan','person-dress'],'stat_dusun'=>['Dusun','map'],'stat_rt'=>['RT','signs-post'],'stat_rw'=>['RW','sitemap']];?>
<?php $bn=rows('SELECT * FROM banner WHERE aktif=1 ORDER BY urutan,id DESC');if($bn):?>
<div id="hs" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="5000"><div class="carousel-indicators"><?php foreach($bn as $i=>$b):?><button type="button" data-bs-target="#hs" data-bs-slide-to="<?=$i?>" class="<?=$i?'':'active'?>"></button><?php endforeach;?></div><div class="carousel-inner"><?php foreach($bn as $i=>$b):?><div class="carousel-item <?=$i?'':'active'?>"><?php if($b['link']):?><a href="<?=e($b['link'])?>"><?php endif;?><img src="assets/uploads/<?=e($b['foto'])?>" class="d-block w-100 hero-img" alt="<?=e($b['judul'])?>"><?php if($b['link']):?></a><?php endif;?></div><?php endforeach;?></div>
<button class="carousel-control-prev" type="button" data-bs-target="#hs" data-bs-slide="prev"><span class="carousel-control-prev-icon"></span></button><button class="carousel-control-next" type="button" data-bs-target="#hs" data-bs-slide="next"><span class="carousel-control-next-icon"></span></button></div>
<div class="bg-white text-center py-4 shadow-sm"><div class="container"><h2 class="fw-bold text-hijau">Selamat Datang di Website Resmi Desa <?=s('nama_desa')?></h2><p class="text-muted mb-2">Mewujudkan pelayanan desa yang transparan, cepat, mudah, dan berbasis digital.</p><a href="masyarakat/layanan.php" class="btn btn-hijau me-2">Layanan Desa</a><a href="profil.php" class="btn btn-outline-success rounded-pill">Jelajahi Desa</a></div></div>
<?php else:?>
<section class="hero"><div class="container text-center"><h1 class="fw-bold">Selamat Datang di Website Resmi Desa <?=s('nama_desa')?></h1><p class="lead">Mewujudkan pelayanan desa yang transparan, cepat, mudah, dan berbasis digital.</p><a href="masyarakat/layanan.php" class="btn btn-gold btn-lg me-2">Layanan Desa</a><a href="profil.php" class="btn btn-outline-light btn-lg rounded-pill">Jelajahi Desa</a></div></section>
<?php endif;?>
<a href="pengaduan.php" class="fab-aduan"><i class="fa fa-headset"></i> Pengaduan</a>
<div class="container"><div class="row g-3 mt-n5 pt-4"><?php foreach($st as $k=>[$l,$i]):?><div class="col-6 col-md-3 col-lg"><div class="card-desa bg-white stat"><i class="fa fa-<?=$i?>"></i><h3><?=number_format((int)($S[$k]??0),0,',','.')?></h3><small><?=$l?></small></div></div><?php endforeach;?></div>
<h3 class="judul">Layanan Desa</h3><div class="row g-3"><?php foreach(rows('SELECT * FROM layanan LIMIT 6') as $l):?><div class="col-md-4"><a href="masyarakat/pengajuan.php?id=<?=$l['id']?>" class="text-decoration-none"><div class="card-desa bg-white p-3"><i class="fa fa-file-lines text-gold fa-lg"></i> <b class="text-hijau"><?=e($l['nama'])?></b><p class="small text-muted mb-0"><?=e($l['deskripsi'])?></p></div></a></div><?php endforeach;?></div>
<div class="text-center mt-3"><a href="masyarakat/layanan.php" class="btn btn-hijau">Semua Layanan</a> <a href="masyarakat/cek-status.php" class="btn btn-outline-success rounded-pill">Cek Status</a></div>
<h3 class="judul">Berita Terbaru</h3><div class="row g-3"><?php foreach(rows('SELECT b.*,k.nama kat FROM berita b JOIN kategori_berita k ON k.id=b.kategori_id ORDER BY headline DESC,tanggal DESC,id DESC LIMIT 3') as $b):?><div class="col-md-4"><a href="berita.php?id=<?=$b['id']?>" class="text-decoration-none text-dark"><div class="card-desa bg-white"><?php if($b['foto']):?><img class="thumb" src="assets/uploads/<?=e($b['foto'])?>"><?php else:?><div class="thumb"></div><?php endif;?><div class="p-3"><span class="badge bg-success"><?=e($b['kat'])?></span><h6 class="mt-2"><?=e($b['judul'])?></h6><small class="text-muted"><?=e($b['tanggal'])?></small></div></div></a></div><?php endforeach;?></div>
<h3 class="judul">Agenda Desa</h3><div class="row g-3"><?php foreach(rows('SELECT * FROM agenda WHERE tanggal>=CURDATE() ORDER BY tanggal LIMIT 4') as $a):?><div class="col-md-3"><div class="card-desa bg-white p-3"><b class="text-hijau"><?=e($a['judul'])?></b><br><small><i class="fa fa-calendar"></i> <?=e($a['tanggal'])?><br><i class="fa fa-location-dot"></i> <?=e($a['lokasi'])?></small></div></div><?php endforeach;?></div></div>
<?php include 'includes/footer.php';?>
